### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by JSEHV** [a-dekker/welkweer#3]
I'd like to suggest an icon that fits well in the Sailfish OS design style, plus reflects colors of The Netherlands. The flag colors are a bit more subtle, but the missing orange is given a nice place. Hope you appreciate the effort.

![harbour-welkweer-172x172](https://user-images.githubusercontent.com/5128988/50174945-dbd92a00-02fb-11e9-8ba4-7844bc38cac8.png)

All sizes:

[harbour-welkweer.zip](https://github.com/a-dekker/welkweer/files/2691784/harbour-welkweer.zip)

**Comment by a-dekker** [comment]
I think I slightly prefer the stripes version over the drops. This will be the third icon for this app ;)
Thanks!

**Comment by Olf0** [comment]
Wow @JSEHV, when reading the changelog in Storeman before updating I thought, "Why another icon, the old (second) one was absolutely fine!".
But the distinctively Dutch rain is extremely cool, so this definitely is an improvement.  I am also glad that @a-dekker picked the striped version (instead of the dotted one), as this resembles the flag more closely.

The only thing I wondered about is the color gradient in the background:
On my Jolla 1 phone (with its worn out and initially already mediocre display) it runs from white (at the top) to a greyish dark yellow (at the bottom).  On an Xperia X the bottom color has more red hues, but still lacks color-saturation to really resemble an orange.
If it would run from white to real oranje, the rain would also fall on (easier to recognise) Netherland-ish ground (just a spontaneous suggestion).

*Edit:* Maybe using a non-linear color gradient (steeper in the bottom area and also gaining color saturation there, i.e. with less grey mixed in) helps to display a more saturated orange there, without being too saturated (i.e., colorful) in the upper three quarters of the icon.  E.g., by using two gradients having the same colour where they meet at about 80% of the distance from top to bottom.
